/* Lógico_1: */

CREATE TABLE CLIENTES (
    COD_CLIENTE INT PRIMARY KEY,
    SOBRENOME STRING,
    NOME STRING,
    INICIAL CHAR,
    DDD INT,
    TELEFONE INT,
    SALDO INT
);

CREATE TABLE FATURAS (
    NUM_FATURA INT PRIMARY KEY,
    DATA_FATURA INT,
    FK_CLIENTES_COD_CLIENTE INT
);

CREATE TABLE LINHAS (
    NUM_LINHAS INT PRIMARY KEY,
    UNIDADES INT,
    VALOR_LI INT,
    FK_FATURAS_NUM_FATURA INT,
    FK_PRODUTOS_COD_PRODUTO INT
);

CREATE TABLE PRODUTOS (
    COD_PRODUTO INT PRIMARY KEY,
    DATA_COMPRA INT,
    DESCRICAO STRING,
    QUANTIDADE INT,
    VALOR_PRO INT,
    FK_FORNECEDORES_COD_FORNECEDOR INT
);

CREATE TABLE FORNECEDORES (
    COD_FORNECEDOR INT PRIMARY KEY,
    NOME STRING,
    CONTATO INT,
    DDD INT,
    TELEFONE INT,
    ESTADO INT
);
 
ALTER TABLE FATURAS ADD CONSTRAINT FK_FATURAS_2
    FOREIGN KEY (FK_CLIENTES_COD_CLIENTE)
    REFERENCES CLIENTES (COD_CLIENTE)
    ON DELETE CASCADE;
 
ALTER TABLE LINHAS ADD CONSTRAINT FK_LINHAS_2
    FOREIGN KEY (FK_FATURAS_NUM_FATURA)
    REFERENCES FATURAS (NUM_FATURA)
    ON DELETE RESTRICT;
 
ALTER TABLE LINHAS ADD CONSTRAINT FK_LINHAS_3
    FOREIGN KEY (FK_PRODUTOS_COD_PRODUTO)
    REFERENCES PRODUTOS (COD_PRODUTO)
    ON DELETE CASCADE;
 
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_2
    FOREIGN KEY (FK_FORNECEDORES_COD_FORNECEDOR)
    REFERENCES FORNECEDORES (COD_FORNECEDOR)
    ON DELETE CASCADE;